<?php
require __DIR__.'/../config/auth.php';requireLogin();require __DIR__.'/../config/db.php';requireDocumentManager($pdo);require __DIR__.'/../config/layout.php';verify_csrf();
$msg='';$err='';$uploads=dirname(__DIR__,2).'/uploads/';$sectores=sectoresEditables($pdo);if(!$sectores){http_response_code(403);exit('No tenés sectores habilitados para editar.');}$sectorIds=array_map(fn($s)=>(int)$s['id'],$sectores);$sid=(int)($_REQUEST['sector_id']??$sectorIds[0]);if(!in_array($sid,$sectorIds,true))$sid=$sectorIds[0];
function folderDescendants(PDO $pdo,int $sid,int $id): array {$out=[];$queue=[$id];while($queue){$current=array_shift($queue);$st=$pdo->prepare('SELECT id FROM carpetas WHERE sector_id=? AND carpeta_padre_id=?');$st->execute([$sid,$current]);foreach($st->fetchAll(PDO::FETCH_COLUMN) as $child){$child=(int)$child;$out[]=$child;$queue[]=$child;}}return$out;}
function folderFlat(PDO $pdo,int $sid): array {$st=$pdo->prepare('SELECT id,nombre,carpeta_padre_id,orden,activa FROM carpetas WHERE sector_id=? AND activa=1 ORDER BY orden,nombre');$st->execute([$sid]);$all=$st->fetchAll();$by=[];foreach($all as $f)$by[$f['carpeta_padre_id']??0][]=$f;$out=[];$walk=function($p,$prefix,$level)use(&$walk,&$out,&$by){foreach($by[$p]??[] as $f){$f['label']=$prefix.$f['nombre'];$f['level']=$level;$out[]=$f;$walk($f['id'],$prefix.'— ',$level+1);}};$walk(0,'',0);return$out;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!puedeEditarSector($pdo,$sid)){http_response_code(403);exit('No tenés permiso de edición para este sector.');}
 $action=$_POST['accion']??'';
 try{
  if($action==='crear'){$name=trim($_POST['nombre']??'');$parent=!empty($_POST['carpeta_padre_id'])?(int)$_POST['carpeta_padre_id']:null;if($name==='')throw new RuntimeException('Ingresá un nombre.');if($parent){$st=$pdo->prepare('SELECT 1 FROM carpetas WHERE id=? AND sector_id=?');$st->execute([$parent,$sid]);if(!$st->fetchColumn())throw new RuntimeException('La carpeta padre no corresponde al sector.');}$pdo->prepare('INSERT INTO carpetas(sector_id,nombre,carpeta_padre_id,orden,activa) VALUES(?,?,?,?,1)')->execute([$sid,mb_substr($name,0,160),$parent,(int)($_POST['orden']??0)]);registrarActividad($pdo,'crear_carpeta',$name);$msg='Carpeta creada.';}
  if($action==='editar'){$id=(int)($_POST['id']??0);$name=trim($_POST['nombre']??'');$parent=!empty($_POST['carpeta_padre_id'])?(int)$_POST['carpeta_padre_id']:null;if($id<=0||$name==='')throw new RuntimeException('Datos incompletos.');if($parent===$id)throw new RuntimeException('Una carpeta no puede depender de sí misma.');$desc=folderDescendants($pdo,$sid,$id);if($parent&&in_array($parent,$desc,true))throw new RuntimeException('No se puede mover una carpeta dentro de una subcarpeta propia.');$pdo->prepare('UPDATE carpetas SET nombre=?,carpeta_padre_id=?,orden=? WHERE id=? AND sector_id=?')->execute([mb_substr($name,0,160),$parent,(int)($_POST['orden']??0),$id,$sid]);registrarActividad($pdo,'editar_carpeta',$name);$msg='Carpeta actualizada.';}
  if($action==='eliminar'){$id=(int)($_POST['id']??0);$ids=array_merge([$id],folderDescendants($pdo,$sid,$id));$ph=implode(',',array_fill(0,count($ids),'?'));$st=$pdo->prepare("SELECT archivo FROM documentos WHERE sector_id=? AND carpeta_id IN ($ph)");$st->execute([$sid,...$ids]);$files=$st->fetchAll(PDO::FETCH_COLUMN);$pdo->beginTransaction();$pdo->prepare("DELETE FROM documentos WHERE sector_id=? AND carpeta_id IN ($ph)")->execute([$sid,...$ids]);$pdo->prepare("DELETE FROM carpetas WHERE sector_id=? AND id IN ($ph)")->execute([$sid,...$ids]);$pdo->commit();foreach($files as $f){if($f&&is_file($uploads.basename($f)))@unlink($uploads.basename($f));}registrarActividad($pdo,'eliminar_carpeta',"Carpeta $id y ".(count($ids)-1).' subcarpetas');$msg='Carpeta eliminada con todas sus subcarpetas y documentos.';}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$err=$e->getMessage();}
}
$folders=folderFlat($pdo,$sid);$selectedSector=array_values(array_filter($sectores,fn($s)=>(int)$s['id']===$sid))[0]??$sectores[0];
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Carpetas | NASER</title><link rel="stylesheet" href="<?=app_url('/style.css')?>"></head><body><div class="app"><?php sidebar($pdo,'carpetas');?><main class="content"><header class="section-top"><div><p class="eyebrow">GESTIÓN DOCUMENTAL</p><h1>Carpetas y subcarpetas</h1><p>Creá, mové, renombrá y eliminá estructuras completas.</p></div><a class="btn primary" href="<?=app_url('/php/admin/documentos.php?sector_id='.$sid)?>">Cargar documentos</a></header><?php if($msg):?><div class="alert success"><?=h($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=h($err)?></div><?php endif;?><form method="get" class="sector-picker"><label>Sector a gestionar<select name="sector_id" onchange="this.form.submit()"><?php foreach($sectores as $s):?><option value="<?=$s['id']?>" <?=(int)$s['id']===$sid?'selected':''?>><?=h($s['nombre'])?></option><?php endforeach;?></select></label></form>
<div class="admin-layout"><section class="form-panel"><p class="eyebrow">NUEVA CARPETA</p><h2>Crear carpeta</h2><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="accion" value="crear"><input type="hidden" name="sector_id" value="<?=$sid?>"><label>Nombre<input name="nombre" required placeholder="Ej: Procedimientos operativos"></label><label>Dentro de<select name="carpeta_padre_id"><option value="">Raíz de <?=h($selectedSector['nombre'])?></option><?php foreach($folders as $f):?><option value="<?=$f['id']?>"><?=h($f['label'])?></option><?php endforeach;?></select></label><label>Orden<input type="number" name="orden" value="0"></label><button class="btn primary">Crear carpeta</button></form></section><section class="table-panel"><div class="section-head"><div><p class="eyebrow">ESTRUCTURA</p><h2><?=h($selectedSector['nombre'])?></h2></div><span class="count-pill"><?=count($folders)?> carpeta(s)</span></div><?php if(!$folders):?><div class="empty">Todavía no hay carpetas.</div><?php endif;?><div class="folder-admin-list"><?php foreach($folders as $f):?><details class="folder-admin-item"><summary><span><?=str_repeat('&nbsp;&nbsp;',min(4,$f['level']))?>📁 <?=h($f['nombre'])?></span><small>Editar</small></summary><form method="post" class="folder-edit"><?=csrf_field()?><input type="hidden" name="accion" value="editar"><input type="hidden" name="sector_id" value="<?=$sid?>"><input type="hidden" name="id" value="<?=$f['id']?>"><div class="form-row"><label>Nombre<input name="nombre" value="<?=h($f['nombre'])?>" required></label><label>Mover dentro de<select name="carpeta_padre_id"><option value="">Raíz</option><?php foreach($folders as $p):if((int)$p['id']===(int)$f['id'])continue;?><option value="<?=$p['id']?>" <?=(int)($f['carpeta_padre_id']??0)===(int)$p['id']?'selected':''?>><?=h($p['label'])?></option><?php endforeach;?></select></label><label>Orden<input type="number" name="orden" value="<?=$f['orden']?>"></label></div><div class="table-actions"><button class="btn secondary">Guardar cambios</button></form><form method="post" onsubmit="return confirm('¿Eliminar esta carpeta, TODAS sus subcarpetas y documentos?')"><?=csrf_field()?><input type="hidden" name="accion" value="eliminar"><input type="hidden" name="sector_id" value="<?=$sid?>"><input type="hidden" name="id" value="<?=$f['id']?>"><button class="btn danger" type="submit">Eliminar completa</button></form></div></details><?php endforeach;?></div></section></div></main></div></body></html>
