<?php
require __DIR__.'/../config/auth.php';requireLogin();require __DIR__.'/../config/db.php';requireDocumentManager($pdo);require __DIR__.'/../config/layout.php';
verify_csrf();
$msg='';$err='';$uploads=dirname(__DIR__,2).'/uploads/';if(!is_dir($uploads))mkdir($uploads,0775,true);
$sectores=sectoresEditables($pdo);if(!$sectores){http_response_code(403);exit('No tenés sectores habilitados para editar.');}
$sectorIds=array_map(fn($s)=>(int)$s['id'],$sectores);$sid=(int)($_REQUEST['sector_id']??$sectorIds[0]);if(!in_array($sid,$sectorIds,true))$sid=$sectorIds[0];

function cleanFolderName(string $s): string {$s=trim(str_replace('\\','/',$s),'/ ');$s=preg_replace('/[^\pL\pN _().-]+/u','_',$s);return mb_substr(trim($s),0,160);}
function findOrCreateFolder(PDO $pdo,int $sid,string $name,?int $parent): int {$name=cleanFolderName($name);if($name==='')throw new RuntimeException('Nombre de carpeta vacío.');if($parent===null){$st=$pdo->prepare('SELECT id FROM carpetas WHERE sector_id=? AND nombre=? AND carpeta_padre_id IS NULL LIMIT 1');$st->execute([$sid,$name]);}else{$st=$pdo->prepare('SELECT id FROM carpetas WHERE sector_id=? AND nombre=? AND carpeta_padre_id=? LIMIT 1');$st->execute([$sid,$name,$parent]);}$id=$st->fetchColumn();if($id){$pdo->prepare('UPDATE carpetas SET activa=1 WHERE id=?')->execute([$id]);return(int)$id;}$pdo->prepare('INSERT INTO carpetas(sector_id,nombre,carpeta_padre_id,orden,activa) VALUES(?,?,?,?,1)')->execute([$sid,$name,$parent,999]);return(int)$pdo->lastInsertId();}
function createFolderPath(PDO $pdo,int $sid,array $parts,?int $base=null): ?int {$parent=$base;foreach($parts as $p){$p=cleanFolderName($p);if($p==='')continue;$parent=findOrCreateFolder($pdo,$sid,$p,$parent);}return$parent;}
function allowedExt(string $name): bool {return in_array(strtolower(pathinfo($name,PATHINFO_EXTENSION)),['pdf','doc','docx','xls','xlsx','ppt','pptx','jpg','jpeg','png','csv','txt'],true);}
function officeTemp(string $name): bool {$b=basename(str_replace('\\','/',$name));return str_starts_with($b,'~$')||str_starts_with($b,'.~lock.')||$b==='.DS_Store';}
function duplicateDoc(PDO $pdo,int $sid,?int $folder,string $title,string $ext): bool {if($folder===null){$st=$pdo->prepare('SELECT archivo FROM documentos WHERE sector_id=? AND carpeta_id IS NULL AND titulo=? AND activo=1');$st->execute([$sid,$title]);}else{$st=$pdo->prepare('SELECT archivo FROM documentos WHERE sector_id=? AND carpeta_id=? AND titulo=? AND activo=1');$st->execute([$sid,$folder,$title]);}foreach($st->fetchAll(PDO::FETCH_COLUMN) as $a){if(strtolower(pathinfo((string)$a,PATHINFO_EXTENSION))===$ext)return true;}return false;}
function saveDoc(PDO $pdo,int $sid,?int $folder,string $source,string $original,string $type,string $state,string $version,?string $expires,string $uploads): bool {if(officeTemp($original)||!allowedExt($original))return false;$ext=strtolower(pathinfo($original,PATHINFO_EXTENSION));$title=trim(pathinfo(basename($original),PATHINFO_FILENAME));if($title===''||duplicateDoc($pdo,$sid,$folder,$title,$ext))return false;$safe=preg_replace('/[^a-zA-Z0-9_-]+/','_',pathinfo($original,PATHINFO_FILENAME));$stored=date('Ymd_His').'_'.bin2hex(random_bytes(4)).'_'.$safe.'.'.$ext;$dest=$uploads.$stored;$ok=is_uploaded_file($source)?move_uploaded_file($source,$dest):copy($source,$dest);if(!$ok)return false;$st=$pdo->prepare('INSERT INTO documentos(sector_id,carpeta_id,titulo,descripcion,tipo,archivo,nombre_original,activo,fecha_actualizacion,estado,version,fecha_vencimiento,creado_por) VALUES(?,?,?,?,?,?,?,1,CURDATE(),?,?,?,?)');$st->execute([$sid,$folder,$title,'',$type,$stored,basename($original),$state,$version,$expires?:null,$_SESSION['usuario_id']??null]);return true;}
function foldersFlat(PDO $pdo,int $sid): array {$st=$pdo->prepare('SELECT id,nombre,carpeta_padre_id,orden FROM carpetas WHERE sector_id=? AND activa=1 ORDER BY orden,nombre');$st->execute([$sid]);$all=$st->fetchAll();$by=[];foreach($all as $f)$by[$f['carpeta_padre_id']??0][]=$f;$out=[];$walk=function($parent,$prefix)use(&$walk,&$by,&$out){foreach($by[$parent]??[] as $f){$out[]=['id'=>$f['id'],'label'=>$prefix.$f['nombre']];$walk($f['id'],$prefix.'— ');}};$walk(0,'');return$out;}

$action=$_POST['accion']??'';
if($_SERVER['REQUEST_METHOD']==='POST'&&in_array($action,['subir_archivos','subir_carpeta','subir_zip','eliminar_documento'],true)){
 if(!puedeEditarSector($pdo,$sid)){http_response_code(403);exit('No tenés permiso de edición para este sector.');}
 try{
  if($action==='eliminar_documento'){$id=(int)($_POST['documento_id']??0);$st=$pdo->prepare('SELECT id,archivo,titulo FROM documentos WHERE id=? AND sector_id=? LIMIT 1');$st->execute([$id,$sid]);$d=$st->fetch();if(!$d)throw new RuntimeException('Documento no encontrado.');$pdo->beginTransaction();$pdo->prepare('DELETE FROM documentos WHERE id=?')->execute([$id]);$pdo->commit();if($d['archivo']&&is_file($uploads.basename($d['archivo'])))@unlink($uploads.basename($d['archivo']));registrarActividad($pdo,'eliminar_documento',$d['titulo']);$msg='Documento eliminado correctamente.';}
  if(in_array($action,['subir_archivos','subir_carpeta'],true)){$base=!empty($_POST['carpeta_id'])?(int)$_POST['carpeta_id']:null;$type=$_POST['tipo']??'documentacion';$state=$_POST['estado']??'aprobado';$version=trim($_POST['version']??'1.0')?:'1.0';$expires=$_POST['fecha_vencimiento']??null;$files=$_FILES['archivos']??null;if(!$files)throw new RuntimeException('No se recibieron archivos.');$ok=$skip=0;$paths=$_POST['rutas']??[];foreach((array)$files['name'] as $i=>$name){if(($files['error'][$i]??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK){$skip++;continue;}$folder=$base;if($action==='subir_carpeta'){$relative=str_replace('\\','/',$paths[$i]??$name);$parts=array_values(array_filter(explode('/',trim($relative,'/')),fn($v)=>$v!==''));array_pop($parts);if($parts)$folder=createFolderPath($pdo,$sid,$parts,$base);}if(saveDoc($pdo,$sid,$folder,$files['tmp_name'][$i],$name,$type,$state,$version,$expires,$uploads))$ok++;else$skip++;}registrarActividad($pdo,'carga_documentos',"Sector $sid: $ok cargados, $skip omitidos");$msg="$ok documento(s) cargados. $skip omitido(s) por duplicado, extensión o error.";}
  if($action==='subir_zip'){$base=!empty($_POST['carpeta_id'])?(int)$_POST['carpeta_id']:null;$type=$_POST['tipo']??'documentacion';$state=$_POST['estado']??'aprobado';$version=trim($_POST['version']??'1.0')?:'1.0';$expires=$_POST['fecha_vencimiento']??null;if(!class_exists('ZipArchive'))throw new RuntimeException('ZipArchive no está disponible. Reconstruí Docker con el Dockerfile incluido.');if(!isset($_FILES['zip'])||$_FILES['zip']['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Seleccioná un ZIP válido.');$zip=new ZipArchive();if($zip->open($_FILES['zip']['tmp_name'])!==true)throw new RuntimeException('No se pudo abrir el ZIP.');$ok=$skip=0;$cache=[];for($i=0;$i<$zip->numFiles;$i++){$entry=$zip->getNameIndex($i);if($entry===false)continue;$entry=str_replace('\\','/',$entry);if(str_starts_with($entry,'__MACOSX/')||str_contains($entry,'../')||str_contains($entry,'/.DS_Store'))continue;$isDir=str_ends_with($entry,'/');$parts=array_values(array_filter(explode('/',trim($entry,'/')),fn($v)=>$v!==''));if(!$parts)continue;if($isDir){$key=implode('/',$parts);if(!isset($cache[$key]))$cache[$key]=createFolderPath($pdo,$sid,$parts,$base);continue;}$name=array_pop($parts);$folder=$base;if($parts){$key=implode('/',$parts);if(!isset($cache[$key]))$cache[$key]=createFolderPath($pdo,$sid,$parts,$base);$folder=$cache[$key];}if(officeTemp($name)||!allowedExt($name)){$skip++;continue;}$tmp=tempnam(sys_get_temp_dir(),'naserzip_');$content=$zip->getFromIndex($i);if($tmp===false||$content===false){$skip++;continue;}file_put_contents($tmp,$content);if(saveDoc($pdo,$sid,$folder,$tmp,$name,$type,$state,$version,$expires,$uploads))$ok++;else$skip++;@unlink($tmp);}$zip->close();registrarActividad($pdo,'carga_zip',"Sector $sid: $ok cargados, $skip omitidos");$msg="ZIP importado: $ok documento(s) cargados y $skip omitido(s).";}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$err=$e->getMessage();}
}
$folders=foldersFlat($pdo,$sid);$st=$pdo->prepare('SELECT d.*,c.nombre carpeta FROM documentos d LEFT JOIN carpetas c ON c.id=d.carpeta_id WHERE d.sector_id=? ORDER BY d.id DESC LIMIT 150');$st->execute([$sid]);$docs=$st->fetchAll();$selectedSector=array_values(array_filter($sectores,fn($s)=>(int)$s['id']===$sid))[0]??$sectores[0];
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Carga documental | NASER</title><link rel="stylesheet" href="<?=app_url('/style.css')?>"></head><body><div class="app"><?php sidebar($pdo,'documentos');?><main class="content"><header class="section-top"><div><p class="eyebrow">GESTIÓN DOCUMENTAL</p><h1>Carga de documentos</h1><p>Carga individual, múltiple, carpetas completas o archivos ZIP conservando la estructura.</p></div><a class="btn secondary" href="<?=app_url('/php/sector.php?sector='.urlencode($selectedSector['slug']))?>">Ver sector</a></header><?php if($msg):?><div class="alert success"><?=h($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=h($err)?></div><?php endif;?>
<form method="get" class="sector-picker"><label>Sector a gestionar<select name="sector_id" onchange="this.form.submit()"><?php foreach($sectores as $s):?><option value="<?=$s['id']?>" <?=(int)$s['id']===$sid?'selected':''?>><?=h($s['nombre'])?></option><?php endforeach;?></select></label></form>
<div class="upload-grid"><section class="form-panel"><p class="eyebrow">ARCHIVOS</p><h2>Uno o varios archivos</h2><form method="post" enctype="multipart/form-data" class="form-grid"><?=csrf_field()?><input type="hidden" name="accion" value="subir_archivos"><input type="hidden" name="sector_id" value="<?=$sid?>"><label>Carpeta destino<select name="carpeta_id"><option value="">Raíz del sector</option><?php foreach($folders as $f):?><option value="<?=$f['id']?>"><?=h($f['label'])?></option><?php endforeach;?></select></label><label>Archivos<input type="file" name="archivos[]" multiple required></label><?=documentMetaFields()?><button class="btn primary">Cargar archivos</button></form></section>
<section class="form-panel"><p class="eyebrow">CARPETA COMPLETA</p><h2>Importar carpetas y subcarpetas</h2><p class="muted">Chrome/Edge envían la ruta relativa de cada archivo y el sistema reconstruye la estructura.</p><form id="folderForm" method="post" enctype="multipart/form-data" class="form-grid"><?=csrf_field()?><input type="hidden" name="accion" value="subir_carpeta"><input type="hidden" name="sector_id" value="<?=$sid?>"><label>Carpeta base<select name="carpeta_id"><option value="">Raíz del sector</option><?php foreach($folders as $f):?><option value="<?=$f['id']?>"><?=h($f['label'])?></option><?php endforeach;?></select></label><label>Seleccionar carpeta<input id="folderInput" type="file" name="archivos[]" webkitdirectory directory multiple required></label><div id="paths"></div><?=documentMetaFields()?><button class="btn primary">Cargar carpeta completa</button></form></section>
<section class="form-panel"><p class="eyebrow">ZIP</p><h2>Importar archivo ZIP</h2><p class="muted">Preserva carpetas, subcarpetas y omite archivos temporales o duplicados.</p><form method="post" enctype="multipart/form-data" class="form-grid"><?=csrf_field()?><input type="hidden" name="accion" value="subir_zip"><input type="hidden" name="sector_id" value="<?=$sid?>"><label>Carpeta base<select name="carpeta_id"><option value="">Raíz del sector</option><?php foreach($folders as $f):?><option value="<?=$f['id']?>"><?=h($f['label'])?></option><?php endforeach;?></select></label><label>Archivo ZIP<input type="file" name="zip" accept=".zip,application/zip" required></label><?=documentMetaFields()?><button class="btn primary">Importar ZIP</button></form></section></div>
<section class="table-panel"><div class="section-head"><div><p class="eyebrow">DOCUMENTOS</p><h2>Últimas cargas de <?=h($selectedSector['nombre'])?></h2></div><a class="btn secondary" href="<?=app_url('/php/admin/carpetas.php?sector_id='.$sid)?>">Administrar carpetas</a></div><div class="table-wrap"><table><thead><tr><th>Documento</th><th>Carpeta</th><th>Tipo</th><th>Versión</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($docs as $d):?><tr><td><strong><?=h($d['titulo'])?></strong><small><?=h($d['nombre_original']??'')?></small></td><td><?=h($d['carpeta']??'Raíz')?></td><td><?=h($d['tipo'])?></td><td><?=h($d['version'])?></td><td><span class="status-pill <?=h($d['estado'])?>"><?=h($d['estado'])?></span></td><td><div class="table-actions"><?php if($d['archivo']):?><a class="btn small secondary" target="_blank" href="<?=app_url('/uploads/'.rawurlencode($d['archivo']))?>">Abrir</a><?php endif;?><form method="post" onsubmit="return confirm('¿Eliminar este documento y su archivo físico?')"><?=csrf_field()?><input type="hidden" name="accion" value="eliminar_documento"><input type="hidden" name="sector_id" value="<?=$sid?>"><input type="hidden" name="documento_id" value="<?=$d['id']?>"><button class="btn small danger">Eliminar</button></form></div></td></tr><?php endforeach;?></tbody></table></div></section>
</main></div><script>const fi=document.getElementById('folderInput'),paths=document.getElementById('paths');if(fi){fi.addEventListener('change',()=>{paths.innerHTML='';[...fi.files].forEach(f=>{const i=document.createElement('input');i.type='hidden';i.name='rutas[]';i.value=f.webkitRelativePath||f.name;paths.appendChild(i)})})}</script></body></html>
<?php
function documentMetaFields(): string {return '<div class="form-row"><label>Tipo<select name="tipo"><option value="documentacion">Documentación</option><option value="procedimiento">Procedimiento</option><option value="formulario">Formulario</option><option value="registro">Registro</option><option value="checklist">Checklist</option><option value="certificado">Certificado</option><option value="otro">Otro</option></select></label><label>Estado<select name="estado"><option value="aprobado">Aprobado</option><option value="revision">En revisión</option><option value="borrador">Borrador</option><option value="obsoleto">Obsoleto</option></select></label></div><div class="form-row"><label>Versión<input name="version" value="1.0"></label><label>Vencimiento<input type="date" name="fecha_vencimiento"></label></div>';}
?>
